name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: intel/oneapi-basekit

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install -y libeigen3-dev wget gnupg2

    - name: cmake
      run: CXX=clang++ cmake .
       
    - name: make
      run: make
    - name: Run with 2 processes
      run: ./demos/matvecmain && mpirun -n 2 ./demos/matvecmain
