name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install -y libmpich-dev libeigen3-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: Run with 2 processes
      run: ./demos/matvecmain && OMP_NUM_THREADS=1 mpirun -n 2 ./demos/matvecmain
